"""Create user Table.

Revision ID: 055b5a8521e5
Revises: 543e487932eb
Create Date: 2024-10-08 18:35:29.845952

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "055b5a8521e5"
down_revision = "543e487932eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("gender", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("profile_picture_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", "banned", name="user_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "role", sa.Enum("admin", "user", name="user_role_enum"), nullable=False
        ),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
